// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package golibevdev

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EvSyn-0]
	_ = x[EvKey-1]
	_ = x[EvRel-2]
	_ = x[EvAbs-3]
	_ = x[EvMsc-4]
	_ = x[EvSw-5]
}

const _EventType_name = "EvSynEvKeyEvRelEvAbsEvMscEvSw"

var _EventType_index = [...]uint8{0, 5, 10, 15, 20, 25, 29}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
