// Code generated by "stringer -type=FFStatusEventCode"; DO NOT EDIT.

package golibevdev

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FfStatusStopped-0]
	_ = x[FfStatusPlaying-1]
	_ = x[FfStatusMax-1]
	_ = x[FfStatusCnt-2]
}

const _FFStatusEventCode_name = "FfStatusStoppedFfStatusPlayingFfStatusCnt"

var _FFStatusEventCode_index = [...]uint8{0, 15, 30, 41}

func (i FFStatusEventCode) String() string {
	if i >= FFStatusEventCode(len(_FFStatusEventCode_index)-1) {
		return "FFStatusEventCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FFStatusEventCode_name[_FFStatusEventCode_index[i]:_FFStatusEventCode_index[i+1]]
}
