// Code generated by "stringer -type=RepeatEventCode"; DO NOT EDIT.

package golibevdev

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RepDelay-0]
	_ = x[RepPeriod-1]
	_ = x[RepMax-1]
	_ = x[RepCnt-2]
}

const _RepeatEventCode_name = "RepDelayRepPeriodRepCnt"

var _RepeatEventCode_index = [...]uint8{0, 8, 17, 23}

func (i RepeatEventCode) String() string {
	if i >= RepeatEventCode(len(_RepeatEventCode_index)-1) {
		return "RepeatEventCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RepeatEventCode_name[_RepeatEventCode_index[i]:_RepeatEventCode_index[i+1]]
}
