// Code generated by "stringer -type=SoundEventCode"; DO NOT EDIT.

package golibevdev

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SndClick-0]
	_ = x[SndBell-1]
	_ = x[SndTone-2]
	_ = x[SndMax-7]
	_ = x[SndCnt-8]
}

const (
	_SoundEventCode_name_0 = "SndClickSndBellSndTone"
	_SoundEventCode_name_1 = "SndMaxSndCnt"
)

var (
	_SoundEventCode_index_0 = [...]uint8{0, 8, 15, 22}
	_SoundEventCode_index_1 = [...]uint8{0, 6, 12}
)

func (i SoundEventCode) String() string {
	switch {
	case i <= 2:
		return _SoundEventCode_name_0[_SoundEventCode_index_0[i]:_SoundEventCode_index_0[i+1]]
	case 7 <= i && i <= 8:
		i -= 7
		return _SoundEventCode_name_1[_SoundEventCode_index_1[i]:_SoundEventCode_index_1[i+1]]
	default:
		return "SoundEventCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
