// Code generated by "stringer -type=SyncEventCode"; DO NOT EDIT.

package golibevdev

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SynReport-0]
	_ = x[SynConfig-1]
	_ = x[SynMTReport-2]
	_ = x[SynDropped-3]
	_ = x[SynMax-15]
	_ = x[SynCnt-16]
}

const (
	_SyncEventCode_name_0 = "SynReportSynConfigSynMTReportSynDropped"
	_SyncEventCode_name_1 = "SynMaxSynCnt"
)

var (
	_SyncEventCode_index_0 = [...]uint8{0, 9, 18, 29, 39}
	_SyncEventCode_index_1 = [...]uint8{0, 6, 12}
)

func (i SyncEventCode) String() string {
	switch {
	case i <= 3:
		return _SyncEventCode_name_0[_SyncEventCode_index_0[i]:_SyncEventCode_index_0[i+1]]
	case 15 <= i && i <= 16:
		i -= 15
		return _SyncEventCode_name_1[_SyncEventCode_index_1[i]:_SyncEventCode_index_1[i+1]]
	default:
		return "SyncEventCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
